### ISSUE TITLE
CORS / implementation question

### ISSUE THREAD

**Issue by kyleferguson** [mainflux/mainflux-core#15]
Playing around with the API I've run into an issue with CORS. (auth API as well)

Curious if you think enabling CORS support on these projects is a good idea, or if your idea of an implementation would involve a server side wrapper that communicates with Mainflux's individual APIs on behalf of the client (in which case that service would handle CORS).

If you like the idea of allowing CORS on these APIs I'd be happy to look into an implementation. Thanks!

**Comment by drasko** [comment]
@kyleferguson all Mainflux services will be behind NGINX proxy. Configuration code is here: https://github.com/mainflux/mainflux-nginx, but it is still in WIP.

Idea with NGINX is to have a load balancer, but for several protocols (MQTT is pure TCP and CoAP is UDP). Besides load balancing, NGINX has to do Auth request forwarding for all HTTP requests.

It will also do TLS and DTLS (for CoAP) termination, so that we can keep certs in one place and simplify the system (at least in the beginning).

In my opinion NGINX would be a good place for CORS support (maybe something like this: https://enable-cors.org/server_nginx.html?).

Do you find this reasonable?

@nmarcetic @mijicd what do you think about this?

**Comment by nmarcetic** [comment]
@kyleferguson @drasko I think we should not solve CORS on service/application layer. In such architectures, this is a responsability of higher layer in stack, such as Load balancer. 
Enabling this in nginx side (while serving as a proxy) will be a good idea for development env.

**Comment by kyleferguson** [comment]
I agree. I had not seen the nginx project yet and was curious about the plans on how to "glue" all the pieces together, but that makes perfect sense now. Thanks!
